package com.zhang.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhang.greendao.dao.Person;
import com.zhang.greendao.dao.PersonFather;

import com.zhang.greendao.dao.PersonDao;
import com.zhang.greendao.dao.PersonFatherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig personFatherDaoConfig;

    private final PersonDao personDao;
    private final PersonFatherDao personFatherDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        personFatherDaoConfig = daoConfigMap.get(PersonFatherDao.class).clone();
        personFatherDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        personFatherDao = new PersonFatherDao(personFatherDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(PersonFather.class, personFatherDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        personFatherDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PersonFatherDao getPersonFatherDao() {
        return personFatherDao;
    }

}
