package com.zhang.greendao.dao;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.zhang.greendao.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSON".
 */
@Entity(active = true)
public class Person {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;
    private Integer age;
    private Long fatherId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient PersonDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "fatherId")
    })
    private List<PersonFather> personFatherList;

    @Generated
    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    @Generated
    public Person(Long id, String name, Integer age, Long fatherId) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.fatherId = fatherId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPersonDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Long getFatherId() {
        return fatherId;
    }

    public void setFatherId(Long fatherId) {
        this.fatherId = fatherId;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<PersonFather> getPersonFatherList() {
        if (personFatherList == null) {
            __throwIfDetached();
            PersonFatherDao targetDao = daoSession.getPersonFatherDao();
            List<PersonFather> personFatherListNew = targetDao._queryPerson_PersonFatherList(id);
            synchronized (this) {
                if(personFatherList == null) {
                    personFatherList = personFatherListNew;
                }
            }
        }
        return personFatherList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetPersonFatherList() {
        personFatherList = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
